# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

$: << File.join(File.dirname(__FILE__), "/../lib")

require 'multiplication_table'

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
end
